return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  main = 'nvim-treesitter.config',
  opts = {
    ensure_installed = {
      'asm',
      'bash',
      'c',
      'cmake',
      'codespell',
      'comment',
      'cpp',
      'css',
      'diff',
      'dockerfile',
      'git_config',
      'git_rebase',
      'gitcommit',
      'gitignore',
      'go',
      'gomod',
      'gosum',
      'graphql',
      'groovy',
      'html',
      'java',
      'javascript',
      'json',
      'json5',
      'lua',
      'luadoc',
      'make',
      'markdown',
      'markdown_inline',
      'prisma',
      'python',
      'query',
      'regex',
      'rust',
      'sql',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    },
    auto_install = true,

    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'batch' },
    },

    indent = { enable = true },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = '<C-space>',
        node_incremental = '<C-space>',
        node_decremental = '<bs>',
        scope_incremental = false,
      },
    },
  },
}
